package domain.entities.actividades;

public enum TiposConsumo {
    GAS_NATURAL,
    DIESEL_GASOIL,
    KEROSENE,
    FUEL_OIL,
    NAFTA,
    CARBON,
    CARBON_DE_LENIA,
    LENIA,
    COMBUSTIBLE_CONSUMIDO_GASOIL,
    COMBUSTIBLE_CONSUMIDO_GNC,
    COMBUSTIBLE_CONSUMIDO_NAFTA,
    ELECTRICIDAD,
    LOGISTICA,
    TRANSPORTE_PUBLICO,
    VEHICULO_PARTICULAR,
    SERVICIO_CONTRATADO,
    BICI_PIE
}
